### PR TITLE
Extract a PreviewResource for displaying the preview

### PR DESCRIPTION
**Pull request by jcoyne**
Because meta-programming is harder to reason about than having regular methods

### CODE REVIEW

**Comment by justinlittman** [comment]
Do you know if the MODS preview still used? If so, where and why?

**Comment by jcoyne** [comment]
@justinlittman Arcadia said:
>I've used it in the past to test how metadata should be structured to achieve a particular result in MODS display, and how display quirks might be rectified.

**Review by justinlittman — APPROVED** [review]
Approve pending green.

**Comment by jcoyne** [comment]
@justinlittman I'm keeping all the green in https://github.com/sul-dlss/purl/pull/738

**Pull request merged**
