### PR TITLE
Update to the latest component library

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Review by thatbudakguy — APPROVED** [review]

**Comment by dnoneill** [comment]
You might want to wait on merging. I think there are still questions if we are going to update all the header/footers at the same time or piecemeal.

**Comment by jcoyne** [comment]
@dnoneill Then we're stuck with this bug? Until when?  Screenshot 2024-12-03 at 8 33 07 AM

**Comment by dnoneill** [comment]
I don't know. I would check with Vivian.

**Comment by cbeer** [comment]
I don't see why fixing the bug and doing a total branding change have to be connected. Can't we just add some CSS to fix it in that app?
https://github.com/sul-dlss/purl/pull/1172

**Comment by jcoyne** [comment]
"total branding change" is just a change of the icon.  This was asked for by the DLUX team: https://github.com/sul-dlss/component-library/issues/55

**Comment by dnoneill** [comment]
Sounds like this can be merged.

**Pull request merged**
