### PR TITLE
Inject ResourceRetriever into PurlVersion to avoid duplication

### LINKED ISSUE #1107: Duplicate fetches of version manifest
```
Processing by PurlController#show as XML
  Parameters: {"id"=>"wp335yr5649", "version"=>"4"}
Fetching wp335yr5649 version_manifest at /Users/jcoyne85/workspace/sul-dlss/purl/spec/fixtures/document_cache/wp/335/yr/5649/wp335yr5649/versions/versions.json (0.1ms)
Fetching wp335yr5649 version_manifest at /Users/jcoyne85/workspace/sul-dlss/purl/spec/fixtures/document_cache/wp/335/yr/5649/wp335yr5649/versions/versions.json (0.0ms)
```

This is in `ResourceRetriever#fetch_resource` It's likely that more than on `ResourceRetriever` is being initialized in the request. We want to prevent this.

### PR DESCRIPTION
**Pull request by aaron-collier**
Fixes #1107 

By injecting a `ResourceRetriever` into `PurlVersion` this removes the need to instantiate a `ResourceRetriever` for each version which causes duplicate fetches of the version manifest when determining if an object is versioned.

Logging confirms the duplicate fetch is removed.

```
Processing by PurlController#show as HTML
  Parameters: {"id"=>"wp335yr5649", "version"=>"3"}
Fetching wp335yr5649 version_manifest at /Users/amcollie/github/sul-dlss/purl/spec/fixtures/document_cache/wp/335/yr/5649/wp335yr5649/versions/versions.json (0.1ms)
Fetching wp335yr5649 public_xml at /Users/amcollie/github/sul-dlss/purl/spec/fixtures/document_cache/wp/335/yr/5649/wp335yr5649/versions/public.3.xml (0.0ms)
```

### CODE REVIEW

**Review by jcoyne — APPROVED** [review]

**Review by jcoyne — CHANGES_REQUESTED** [review]
What if we separate a `VersionedResourceRetriever` from the `ResourceRetriever`?

**Comment by jcoyne** [comment]
Maybe the `ResourceRetriever` can just become the `VersionManifestResource` ?

**Comment by aaron-collier** [comment]
@jcoyne let me think through that, we can obviously hold this for a bit.

**Comment by aaron-collier** [comment]
Replaced by #1118

**Pull request closed without merging**
