### PR TITLE
Add skip link to top of header

### PR DESCRIPTION
**Pull request by jcoyne**
Focused:
Screenshot 2024-06-19 at 1 00 50 PM

Not focused
Screenshot 2024-06-19 at 1 01 02 PM

### CODE REVIEW

**Comment by dnoneill** [comment]
wouldn't it make more sense to wrap the navbars in the <nav> tag and put the skip in with those?

**Comment by jcoyne** [comment]
@dnoneill I want this whole block to tdisappear unless it's focused on, so I think including visible stuff within it, makes that all harder.

**Comment by dnoneill** [comment]
@jcoyne I think? <nav> is supposed to go around the navigation for keyboards: http://web-accessibility.carnegiemuseums.org/code/navigation/ and skip links is in body? http://web-accessibility.carnegiemuseums.org/code/skip-link/.

**Comment by jcoyne** [comment]
@dnoneill This is exactly how it's currently done for Searchworks and our other properties here. It's allowable to have multiple `<nav>` sections on a page.

**Review by dnoneill — APPROVED** [review]

**Pull request merged**
