### PR TITLE
Adds view in EarthWorks link for geo things

### LINKED ISSUE #189: Add "View in EarthWorks" for Geo objects

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #189 

## cg357zz0321

screen shot 2017-12-14 at 8 20 54 am

### CODE REVIEW

**Comment by jkeck** [comment]
This looks good to me.  Worth adding a test?

**Comment by mejackreed** [comment]
Possibly. I think the reason I didn't was that PURL specs have pear tree representation of objects in fixtures. I'm happy to add content type geo if that makes sense here. I held off because it would be  a bigish change.

**Comment by jkeck** [comment]
Ah, yeah, totally understand, that seems like a PITA for such a small change.  Would a view spec be easy enough to write or still a pain?  If so, I'm fine with 🚢ing it.

**Comment by mejackreed** [comment]
Thanks!

**Pull request merged**
