### PR TITLE
Adds almetric badge

### LINKED ISSUE #718: Display Altmetric badge on PURL pages
### proposal
[see proposal in requirements doc](https://docs.google.com/document/d/1W5rmHTMRGso5uxqIKqptvUYVYIn9cUeo6Nm9rx96XTU/edit#heading=h.7d870vk45abw)

- [ ] Modify PURL markup so that it includes the [elements required](https://help.altmetric.com/support/solutions/articles/6000240582-required-metadata-for-content-tracking) for SDR deposits to be tracked by Altmetric. 
  - This must include two of the supported meta tags on Altmetric's list, one of which must be an identifier on [their list](https://help.altmetric.com/support/solutions/articles/6000240585-scholarly-identifiers-supported-by-altmetric) (DOIs are on the list, PURLs are not).
  - They recommend as many of the supported meta tags as possible.
- [ ] Display of Altmetric badges on PURL pages in compliance with [Altmetric guidelines](https://www.altmetric.com/solutions/free-tools/institutional-repository-badges/).
  - [Technical documentation](https://badge-docs.altmetric.com/)
  - Note that since PURL is not one of the identifiers they track, we will only be able to track PURLs that also have a DOI, and tracking will only include mentions of the DOI and not the PURL (in cases where someone used the PURL but not the DOI for a citation).

### user stories
_As a depositor, I would like to see Altmetric badges displayed on my content so that I can better understand the broader impacts of my work and demonstrate this to funders, promotion and tenure committees, potential employers, etc._

_As a university administrator, I would like to see Altmetric information about content from my faculty and other department members so that I can better understand and promote the work of my department, research institute, or school._

### design
- we're using the smallest "donut" design in the options that Altmetric provides.
- the popover on hover should be enabled.
- other details should not be enabled.

Screenshot 2023-10-18 at 12 32 49

[see it in context in the invision mockup](https://projects.invisionapp.com/share/FV13CCPQXMHA#/screens/474686424)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #718

image

### CODE REVIEW

**Comment by justinlittman** [comment]
Note that the altmetrics badge is supposed to appear in a separate statistics section. However, since there are no statistics, I omitted the section and just put the badge on the bottom of the page.

**Comment by justinlittman** [comment]
This is before I get rid of the failure badge:
image

**Comment by justinlittman** [comment]
This is after I get rid of the failure badge:
image

**Comment by jcoyne** [comment]
</img>

**Comment by justinlittman** [comment]
image

**Comment by amyehodge** [comment]
Looks good. Thanks.

**Review by lwrubel — APPROVED** [review]

**Pull request merged**
