### PR TITLE
Support the new style of licenses from h2

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by cbeer** [comment]
For the sake of consistency across our platforms, we probably want to make similar changes to our other repositories too, including:

https://github.com/sul-dlss/sul-embed/search?q=license
https://github.com/sul-dlss/earthworks/search?q=license
https://github.com/sul-dlss/mods_display/blob/master/lib/mods_display/fields/access_condition.rb (maybe?)
https://github.com/sul-dlss/SearchWorks/blob/master/app/assets/stylesheets/modules/license-icons.scss (whatever provides those... maybe mods_display above)?

I think we're also expecting some fixture objects to check out in our various apps to make sure we've covered everything.

**Comment by andrewjbtw** [comment]
I think H2 has been updated or soon will be so that we can make fixtures with the new codes. If not, I can try to make them directly in the XML but I was hoping to use "normal" means to make them.

**Comment by jcoyne** [comment]
I've also added:
- https://github.com/sul-dlss/earthworks/pull/785
- https://github.com/sul-dlss/sul-embed/pull/1265
- https://github.com/sul-dlss/mods_display/pull/79

**Comment by andrewjbtw** [comment]
H2-created fixtures

| License | URL | Purl |
| ------------- | ------------- | -------- |
| AGPL-3.0-only GNU Affero General Public License | https://www.gnu.org/licenses/agpl.txt | https://sul-purl-stage.stanford.edu/xp945mz0673
| Apache-2.0 | http://www.apache.org/licenses/LICENSE-2.0 | https://sul-purl-stage.stanford.edu/xm718mq3288
| BSD-2-Clause "Simplified" License | https://opensource.org/licenses/BSD-2-Clause | https://sul-purl-stage.stanford.edu/fp088tj2603
| BSD-3-Clause "New" or "Revised" License | https://opensource.org/licenses/BSD-3-Clause | https://sul-purl-stage.stanford.edu/gq033jc6981
| CC BY: Attribution International | https://creativecommons.org/licenses/by/4.0/legalcode | https://sul-purl-stage.stanford.edu/bz964by0261
| CC BY-ND: Attribution-No Derivatives International | https://creativecommons.org/licenses/by-nd/4.0/legalcode | https://sul-purl-stage.stanford.edu/vk350jc0817
| CC BY-NC: Attribution-NonCommercial International | https://creativecommons.org/licenses/by-nc/4.0/legalcode | https://sul-purl-stage.stanford.edu/wp959th7839
| CC BY-NC-ND: Attribution-NonCommercial-No Derivatives | https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode | https://sul-purl-stage.stanford.edu/wt025pm1273
| CC BY-NC-SA: Attribution-NonCommercial-Share Alike International | https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode | https://sul-purl-stage.stanford.edu/vr163fs5922
| CC BY-SA: Attribution-Share Alike International | https://creativecommons.org/licenses/by-sa/4.0/legalcode | https://sul-purl-stage.stanford.edu/sx903yj0490
| CC0 - 1.0 | https://creativecommons.org/publicdomain/zero/1.0/legalcode | https://sul-purl-stage.stanford.edu/vk768vs1426
| CDDL-1.1 Common Development and Distribution License | https://opensource.org/licenses/cddl1 | https://sul-purl-stage.stanford.edu/ss409gd5731
| EPL-2.0 Eclipse Public License | https://www.eclipse.org/legal/epl-2.0 | https://sul-purl-stage.stanford.edu/pd127vw4170
| GPL-3.0-only GNU General Public License | https://www.gnu.org/licenses/gpl-3.0-standalone.html | https://sul-purl-stage.stanford.edu/hn036jf1242
| ISC License | https://www.isc.org/downloads/software-support-policy/isc-license/ | https://sul-purl-stage.stanford.edu/rx143sk0299
| LGPL-3.0-only Lesser GNU Public License | https://www.gnu.org/licenses/lgpl-3.0-standalone.html | https://sul-purl-stage.stanford.edu/xd665cs4456
| MIT License | https://opensource.org/licenses/MIT | https://sul-purl-stage.stanford.edu/qh658ks9803
| MPL-2.0 Mozilla Public License | http://www.mozilla.org/MPL/2.0/ | https://sul-purl-stage.stanford.edu/hv454jm8828
| No license selected | left blank - no URL in Purl | https://sul-purl-stage.stanford.edu/dn988zw3373
| ODC odc-by: ODC-By-1.0 Attribution License | https://opendatacommons.org/licenses/by/1-0/ | https://sul-purl-stage.stanford.edu/qh369zd3281
| ODC pddl: Open Data Commons Public Domain Dedication and License (PDDL-1.0) | https://opendatacommons.org/licenses/pddl/1-0/ | https://sul-purl-stage.stanford.edu/rc387hz0372
| ODC odbl: ODbL-1.0 Open Database License | https://opendatacommons.org/licenses/odbl/1-0/ | https://sul-purl-stage.stanford.edu/zr839dt6819

**Comment by andrewjbtw** [comment]
Here's a list of Argo-created items. Argo currently has 11 license options (not including "no license", which is functionally the same as H2's "no license"). All the Argo CC licenses in the Argo menus, except the public domain ones, are 3.0 at the moment. We plan to update that after 4.0 is supported on Purl so that new items can only choose 4.0. But we won't automatically update existing 3.0 items to 4.0 - the content owners will need to do that. So we'll likely have a mix of 3.0 and 4.0 items for a while.

Note that I actually pasted in the "human" and "machine" tags (in rightsMetadata) from prod objects since we don't create these statements automatically anymore when creating new items from scratch. Also, every new item has a license URL because we now insert that upon publish. There isn't a way to create objects in stage that follow the old, non-URL behavior. There is legacy data in production without URLs, but I'm working on republishing/remediating those.

Druid | Purl | Title
----|----|----
bc872mx3995 | https://purl-stage.stanford.edu/bc872mx3995 | Open Data Commons Public Domain Dedication and License 1.0 (with human/machine tags)
bd618qd9334 | https://purl-stage.stanford.edu/bd618qd9334 | Open Data Commons Attribution License 1.0 (with human/machine tags)
bf082xd6873 | https://purl-stage.stanford.edu/bf082xd6873 | Open Data Commons Open Database License 1.0 (with human/machine tags)
bg716cx0275 | https://purl-stage.stanford.edu/bg716cx0275 | CC0, aka "No Rights Reserved" (with human/machine tags)
bh170kx4504 | https://purl-stage.stanford.edu/bh170kx4504 | CC Attribution 3.0 Unported (with human/machine tags)
bj385th6563 | https://purl-stage.stanford.edu/bj385th6563 | CC Attribution Share Alike 3.0 Unported (with human/machine tags)
bj863ns1766 | https://purl-stage.stanford.edu/bj863ns1766 | CC Attribution No Derivatives 3.0 Unported (with human/machine tags)
bk189xs5530 | https://purl-stage.stanford.edu/bk189xs5530 | CC Attribution Non-Commercial 3.0 Unported (with human/machine tags)
bk646xg2213 | https://purl-stage.stanford.edu/bk646xg2213 | CC Attribution Non-Commercial Share Alike 3.0 Unported (with human/machine tags)
bk668jr2643 | https://purl-stage.stanford.edu/bk668jr2643 | CC Attribution Non-Commercial, No Derivatives 3.0 Unported (with human/machine tags)
bm007xr8005 | https://purl-stage.stanford.edu/bm007xr8005 | CC Public Domain Mark 1.0 (with human/machine tags)

**Comment by andrewjbtw** [comment]
I updated my fixture tables so that they use the same column headings and orderings. Also, I added an example of a CC 4.0 item that has the human/machine tags, since users have entered 4.0 licenses manually in our data even though it's not supported in any Argo or Hydrus license selection menu and does not (yet) display properly on the purl.

Currently, the 4.0 data with the old tags still shows a link back to a 3.0 license, but without the old tags, the text display is correct:

4.0 (by-nc) with the human/machine tags in rightsMetadata: https://sul-purl-stage.stanford.edu/bp606ft7703
4.0 (by-nc) with only the license node: https://sul-purl-stage.stanford.edu/wp959th7839

**Comment by jcoyne** [comment]
@mjgiarlo what remediation were you proposing?  I don't think that @andrewjbtw was expecting to have to remediate objects that looked like this: https://sul-purl-stage.stanford.edu/bp606ft7703 (but that don't work in PURL)

**Comment by andrewjbtw** [comment]
We had a brief conversation in Slack. My plan is to leave only the `<license>` node for CC 4.0 objects. Then CC 3 objects can retain the same behavior if anything still uses `<rightsMetadata>` without interfering with CC 4, which would exclusively use the new process.

**Comment by thatbudakguy** [comment]
closing based on slack convo – we think there's no work to do here.

**Pull request closed without merging**
