### PR TITLE
Remove popper js from importmap.rb

### PR DESCRIPTION
**Pull request by justinlittman**
To the best I can tell it isn't used.

### CODE REVIEW

**Comment by jcoyne** [comment]
popper.js is a peer dependency of bootstrap.  Can you remove bootstrap too?

**Comment by justinlittman** [comment]
If I'm not mistaken, all of those BS components are opt-in. And I don't see any indication that we've opted in to any of them.

**Comment by jcoyne** [comment]
@justinlittman I don't see anything about opting in here: https://getbootstrap.com/docs/5.3/components/dropdowns/ All you have to do to opt in is to add the attribute `data-bs-toggle="dropdown"` to a DOM node.

**Comment by justinlittman** [comment]
Dropdowns, popovers, and tooltips aren't used in purl. However, since it is a tiny library, I'm going to close.

**Pull request closed without merging**
