### PR TITLE
Refactor link style to be additive rather than subtractive

### PR DESCRIPTION
**Pull request by jcoyne**
This fixes the double underline in the global footer when hovering.

### CODE REVIEW

**Comment by jcoyne** [comment]
@justinlittman because there are some links on the page where we don't want it. Namely the ones in the global footer where we currently see a double underline.  We also don't want it on links that are images, or in the header.

**Comment by justinlittman** [comment]
Could it just be limited to links in the relevant parts of the page? My concern is that a future dev will add a new link but not think of adding the necessary class.

**Comment by jcoyne** [comment]
@justinlittman at this point it's harder to handle the exceptions rather than to remember to add the one style we want to use. So long as we are using border-bottom for a link style, this gets very challenging.  I think if we went to text-decoration:underline, I could get behind a link style default.

**Comment by justinlittman** [comment]
I defer to your judgment. Thanks for the explanation.

**Review by justinlittman — APPROVED** [review]

**Pull request merged**
